'use client';
import { Btn, Placeholder, Section } from '@/components/ui';import { imageVars, portfolio, services, testimonials } from '@/lib/data';import { motion } from 'framer-motion';import Link from 'next/link';
export default function Home(){return <main><section className='containerx grid lg:grid-cols-2 gap-10 py-20 items-center'><div><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className='text-5xl md:text-7xl font-black leading-tight'>WE BUILD <span className='text-accent'>POWERFUL GYM</span> WEBSITES THAT BUILD YOUR BRAND.</motion.h1><p className='text-white/70 mt-6'>We create high-performance, conversion-focused websites for gyms and fitness studios that drive measurable growth.</p><div className='mt-8 flex gap-3'><Btn href='/contact'>Book a Free Call</Btn><Btn href='/portfolio' secondary>View Our Work</Btn></div><p className='mt-6 text-sm text-white/70'>★★★★★ Trusted by 200+ Fitness Brands</p></div><motion.div animate={{y:[0,-8,0]}} transition={{repeat:Infinity,duration:4}}><Placeholder name={imageVars.heroAthleteImage} className='min-h-[520px] ring-1 ring-accent/40 shadow-glow'/></motion.div></section>
<Section title='Trusted by gym & fitness brands worldwide'><div className='grid grid-cols-2 md:grid-cols-6 gap-4 text-center text-white/70'>{['IRON FITNESS','BEAST MODE','ELITE TRAINING','MAX PERFORMANCE','UNSTOPPABLE GYM','FITNESS LAB'].map(x=><div key={x} className='glass py-4 rounded-xl'>{x}</div>)}</div></Section>
<Section kicker='WHAT WE DO' title='Websites Built for the Fitness Industry'><div className='grid md:grid-cols-4 gap-4'>{services.map(s=><div key={s.title} className='glass p-6 rounded-2xl'><h3 className='font-semibold mb-2'>{s.title}</h3><p className='text-white/70 text-sm'>{s.desc}</p></div>)}</div></Section>
<Section kicker='OUR WORK' title='Websites That Deliver Results'><div className='grid md:grid-cols-4 gap-4'>{portfolio.map(p=><Link href={`/portfolio/${p.slug}`} key={p.slug} className='glass p-3 rounded-2xl'><Placeholder name={p.img}/><h3 className='font-semibold mt-3'>{p.name}</h3><p className='text-sm text-white/70'>{p.summary}</p></Link>)}</div></Section>
<Section kicker='OUR PROCESS' title='Simple Process. Powerful Results.'><div className='grid md:grid-cols-4 gap-4'>{['Discover','Plan & Design','Develop','Launch & Grow'].map((s,i)=><div key={s} className='glass p-6 rounded-2xl'><p className='text-accent'>0{i+1}</p><h3 className='font-semibold'>{s}</h3></div>)}</div></Section>
<Section kicker='WHAT OUR CLIENTS SAY' title='Real Results. Real Relationships.'><div className='grid md:grid-cols-3 gap-4'>{testimonials.map(t=><div key={t.name} className='glass p-6 rounded-2xl'><p>“{t.quote}”</p><p className='mt-4 font-semibold'>{t.name}</p><p className='text-white/70 text-sm'>{t.role}</p></div>)}</div></Section>
<section className='containerx'><div className='glass rounded-3xl p-8 md:p-12 grid md:grid-cols-2 gap-6 items-center'><Placeholder name='ctaAthleteImage' className='min-h-60'/><div><h3 className='text-4xl font-bold'>Ready to Grow Your Gym Online?</h3><p className='text-white/70 my-4'>Get a high-converting website that attracts more members and boosts revenue.</p><div className='flex gap-3'><Btn href='/contact'>Book a Free Call</Btn><Btn href='/contact' secondary>Chat on WhatsApp</Btn></div></div></div></section>
</main>}
